# Description: GPS configuration file
rate: 5
max_noise: 0.1
gps_delay: 1.0
cov: 0.02
manual_integration: false
x_offset: 0
y_offset: 0
# y_offset: -14.96
width: 20.696
# width: 20.541
height: 13.786
# height: 13.656